[package]
name = "pdf_cropper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
image = "0.25.5"
imageproc = "0.25.0"
indicatif = "0.17.11"
pdfium-render = "0.8.28"
